### ISSUE TITLE
Add translatable intro sentence for each tab

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#56]
In addition to #40, each tab should have an optional introduction sentence, e.g.:

data:

> Die analysierten Datensätze können hier durchsucht und gefiltert werden.

completeness:

> Welche Felder und Unterfelder kommen wie häufig in welchen Datensätzen vor?

issues:

> Übereinstimmung mit dem hinterlegten Avram-Schema.

tabs:
- [x] data
- [x] completeness
- [x] issues
- [x] classifications
- [x] authority names
- [x] history
- [x] terms
- [x] collocations
- [x] download
- [x] settings
- [x] about

**Comment by pkiraly** [comment]
There is a general problem I just started to solve. The catalogue-related things like the metadata schema should be separated from the language. So I would avoid to put Avram or PICA into German translation, because there might be cases when someone checks MARC records in German. So I created a variable metadataSchema of the Catalogue object, and made it translatable, and changed the sentence of the issue so that this metadata schema can be injectable:

.po:
```
Übereinstimmung mit dem hinterlegten bibliografischen Metadatenschema (%s). 
```
.tpl:
```
{_t('issues_definition', _($catalogue->getMetadataSchema()))}
```
where `_t()` is a new function which accepts arguments for the translation. I documented this in the README. You can use `sprintf` compatible placeholder, such as `%s`, `%d` etc.
