### ISSUE TITLE
Support customization of about tab

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#73]
I'd like to put a custom text in the about tab to replace the contents of `<div id="about-tab">`. How about adding directory `local/` to `.gitignore` and in `templates/about.tpl` add something like `{if file_exists(local/about-$language,tpl}{include "local/about-$language.tpl"}{else}default text{/if}` I'm not sure how to get the current language. Some minimal static information about the software should always be shown at the bottom.

**Comment by nichtich** [comment]
In branch issue-73 I tried to change the current contents of the about page to be more generic so custom information could be included on top, e.g. background information about the database.

**Comment by pkiraly** [comment]
I like this idea. 

The language is set in the BaseTab:
```php
$this->lang = getOrDefault('lang', $this->catalogue->getDefaultLang(), ['en', 'de']);
```
`getOrDefault` is how we get parameters from the request. 
- The first parameter `lang` here is the name of the parameter, such as in `https://....?lang=en`. 
- The second parameter is the default value if there is no parameter, or there is no valid parameter. Here the $this->catalogue is the class specific for the particular catalogue (e.g. `K10plus_pica`). It might have a default language, which is useually 'en', but K10plus related classes overwrite it to 'de'.
- Th last parameter is an array containing the list of acceptable values. So if somebody would call it with 'fr', since it is not yet defined, the default value will be applied.

The `index.php` defines a `$languages` array, which maps the parameters to the official language code.

The translations are stored in the `locale` directory. There are `.po`, and `.mo` files. The translator should edit the `.po` file, then make the binary `.mo` files programmatically:

```
msgfmt locale/de_DE/LC_MESSAGES/messages.po -o locale/de_DE/LC_MESSAGES/messages.mo
msgfmt locale/en_GB/LC_MESSAGES/messages.po -o locale/en_GB/LC_MESSAGES/messages.mo
```
There are more about this at https://github.com/pkiraly/metadata-qa-marc-web#translation

In templates you should use the `{_("some text")}` function where the "some text" part should be in a `msgid` key in the `.po` file.
